services:
  zabbix-speedtest:
    build: .
    restart: always
    container_name: morkovka-zabbix-speedtest  # Установите уникальное имя контейнера
    privileged: true  # Добавлено, если необходимо использовать привилегированный режим
    volumes:
      - /tmp:/tmp  # Прокидывем папку /tmp, если это необходимо
